#ifndef SENSORS_H_INCLUDED
#define SENSORS_H_INCLUDED

#define MC_NO_ADDR 						0xA0
#define MC_TORQUE_ADDR 					0xA1
#define MC_SUCTION_TEMP_ADDR 			0xA2
#define MC_COOLANT_GOING_TEMP_ADDR 		0xA3
#define MC_COOLANT_RETURN_TEMP_ADDR 	0xA4
#define MC_ENGINE_BLOCK_TEMP_ADDR		0xA5
#define MC_EXHAUST_TEMP_ADDR			0xA6
#define MC_OIL_TEMP_ADDR				0xA7
#define MC_CRANKSHAFT_RPM_ADDR			0xB0
#define MC_FUEL_GOING_ADDR				0xB1
#define MC_FUEL_RETURN_ADDR				0xB2
#define MC_SUCTION_FLOW_ADDR			0xB3
#define MC_BIN_INPUT_1					0xB4
#define MC_REGISTERS_ALL				0xBB

//MC_BIN_INPUT_1 MASKS
#define MC_BIN_INPUT_1_OILPRESSURE_OK	 	0
#define MC_BIN_INPUT_1_EMERG_STOP			1
#define MC_BIN_INPUT_1_MIN_FUEL_LVL			2
#define MC_BIN_INPUT_1_ANNEALING_ON			3



#endif /*SENSORS_H_INCLUDED */